kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretmanager-cr
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch