kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managernodelete-rb
  namespace: team-api
subjects:
- kind: Group
  name: api # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: managernodelete-cr
  apiGroup: rbac.authorization.k8s.io
