kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managertech-rb
  namespace: team-vision
subjects:
- kind: Group
  name: teach-lead # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: manager-cr
  apiGroup: rbac.authorization.k8s.io
