kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretmanager-rb
  namespace: team-vision
subjects:
- kind: Group
  name: sre # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secretmanager-cr
  apiGroup: rbac.authorization.k8s.io
